version: "3.9"

services:

  bot_app:
    hostname: bot_app
    container_name: bot_app
    build: .
    ports: 
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - postgres
    networks:
      - slack_bot

  postgres:
    image: postgres:14.4
    hostname: postgres_db
    container_name: postgres_db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./.env.db
    # volumes:
    #   - postgres-db-dev:/var/lib/postgresql/data
    networks:
      - slack_bot

  adminer:
    image: adminer:4.8.1
    hostname: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - slack_bot

volumes:
  postgres-db-dev:

networks:
  slack_bot:
    name: slack_bot