"""init_db

Revision ID: 62c802166d46
Revises: 
Create Date: 2022-08-08 18:39:08.190211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "62c802166d46"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user", sa.String(length=80), nullable=False),
        sa.Column("message", sa.String(length=120), nullable=False),
        sa.Column("channel", sa.String(length=120), nullable=False),
        sa.Column("channel_type", sa.String(length=120), nullable=False),
        sa.Column("ts", sa.FLOAT(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("thread", sa.BOOLEAN(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scheduled_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scheduled_message_id", sa.String(length=120), nullable=False),
        sa.Column("channel", sa.String(length=120), nullable=False),
        sa.Column("text", sa.String(length=120), nullable=False),
        sa.Column("post_at", sa.FLOAT(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("user", sa.String(length=80), nullable=False),
        sa.Column("channel", sa.String(length=120), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_message",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("scheduled_messages")
    op.drop_table("messages")
    # ### end Alembic commands ###
